apiVersion: v1
kind: Service
metadata:
  name: istio-route-demo-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 18080
      targetPort: 18080
  selector:
    app: istio-route-demo-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-route-demo-server-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-route-demo-server
  template:
    metadata:
      labels:
        app: istio-route-demo-server
        featureTag: v1
    spec:
      containers:
        - name: istio-route-demo-server
          image: docker.io/library/istio-route-demo-server-v1:latest
          imagePullPolicy: IfNotPresent
          tty: true
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-route-demo-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-route-demo-server
  template:
    metadata:
      labels:
        app: istio-route-demo-server
        featureTag: v2
    spec:
      containers:
        - name: istio-route-demo-server
          image: docker.io/library/istio-route-demo-server-v2:latest
          imagePullPolicy: IfNotPresent
          tty: true
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080